[package]
name = "paleobiology"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
draw3d = { path = "../draw3d" }
glam = "0.25.0"
rand = "0.8.5"
